/**
 * exerciseQualifierMap.test.js — integrity of the GENERATED qualifier map.
 *
 * Run: node mobile/src/constants/__tests__/exerciseQualifierMap.test.js
 *
 * exerciseQualifierMap.ts is generated by scripts/gen-qualifier-map.js, which
 * validates as it writes. This suite guards the COMMITTED artifact, because the
 * generator's checks do nothing if someone hand-edits the output (the header
 * says not to, which is not the same as preventing it).
 *
 * Each check maps to a concrete user-visible failure:
 *   1. Unknown axis id            -> a chip the picker cannot render.
 *   2. Value outside the closed vocabulary -> an option with no label or graphic.
 *   3. Default not in its own values -> a chip showing a value you can never pick.
 *   4. 'normalize' with no ratio   -> a percentile divided by undefined.
 *   5. Ratio <= 0 or absurd        -> silently corrupted rankings.
 *   6. Duplicate axis on one exercise -> two chips fighting over one key.
 *   7. Lookup/normalization drift  -> every spec unreachable at runtime.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const REPO = path.resolve(__dirname, '..', '..', '..', '..');
const ts = require(path.join(REPO, 'mobile', 'node_modules', 'typescript'));

function load(relPath, deps) {
  deps = deps || {};
  const src = fs.readFileSync(path.join(REPO, relPath), 'utf8');
  const js = ts.transpileModule(src, {
    compilerOptions: { module: 'commonjs', target: 'es2019', esModuleInterop: true },
  }).outputText;
  const mod = { exports: {} };
  const requireStub = function (id) {
    const key = id.replace(/^\.\//, '').replace(/^\.\.\//, '');
    if (deps[key]) return deps[key];
    if (deps[id]) return deps[id];
    try { return require(id); } catch (_) { return {}; }
  };
  // eslint-disable-next-line no-new-func
  new Function('module', 'exports', 'require', js)(mod, mod.exports, requireStub);
  return mod.exports;
}

const qualifiers = load('mobile/src/constants/qualifiers.ts');
const map = load('mobile/src/constants/exerciseQualifierMap.ts', {
  qualifiers: qualifiers,
  './qualifiers': qualifiers,
});

const { QUALIFIER_AXES, isKnownAxis, isKnownValue } = qualifiers;
const { EXERCISE_QUALIFIERS, qualifierSpecForExercise, defaultsForExercise, normalizeExerciseName } = map;

let passed = 0;
let failed = 0;
function test(name, fn) {
  try { fn(); console.log('  PASS  ' + name); passed++; }
  catch (err) { console.log('  FAIL  ' + name + ' — ' + err.message); failed++; }
}
function assert(c, m) { if (!c) throw new Error(m || 'assertion failed'); }
function eq(a, b, m) {
  if (a !== b) throw new Error((m || '') + ' expected ' + JSON.stringify(a) + ' === ' + JSON.stringify(b));
}

console.log('\nexerciseQualifierMap.test.js\n');

const keys = Object.keys(EXERCISE_QUALIFIERS);

test('the map is non-empty and covers the researched library', () => {
  assert(keys.length > 150, 'expected >150 exercises, got ' + keys.length);
});

test('every axis id is in the closed vocabulary', () => {
  const bad = [];
  for (const k of keys) {
    for (const a of EXERCISE_QUALIFIERS[k].axes) {
      if (!isKnownAxis(a.a)) bad.push(k + ' -> ' + a.a);
    }
  }
  eq(bad.length, 0, 'unknown axes: ' + bad.slice(0, 5).join(', '));
});

test('every value is in its axis vocabulary', () => {
  const bad = [];
  for (const k of keys) {
    for (const a of EXERCISE_QUALIFIERS[k].axes) {
      for (const v of a.v) {
        if (!isKnownValue(a.a, v)) bad.push(k + ' -> ' + a.a + ':' + v);
      }
    }
  }
  eq(bad.length, 0, 'unknown values: ' + bad.slice(0, 5).join(', '));
});

// The one that would render an unselectable chip.
test('every default is one of that axis\'s own applicable values', () => {
  const bad = [];
  for (const k of keys) {
    for (const a of EXERCISE_QUALIFIERS[k].axes) {
      if (!a.v.includes(a.d)) bad.push(k + ' -> ' + a.a + ' default=' + a.d + ' not in [' + a.v.join(',') + ']');
    }
  }
  eq(bad.length, 0, 'bad defaults: ' + bad.slice(0, 5).join(' | '));
});

test('no exercise lists the same axis twice', () => {
  const bad = [];
  for (const k of keys) {
    const seen = new Set();
    for (const a of EXERCISE_QUALIFIERS[k].axes) {
      if (seen.has(a.a)) bad.push(k + ' -> ' + a.a);
      seen.add(a.a);
    }
  }
  eq(bad.length, 0, 'duplicate axes: ' + bad.slice(0, 5).join(', '));
});

test('every axis offers at least one value', () => {
  const bad = [];
  for (const k of keys) {
    for (const a of EXERCISE_QUALIFIERS[k].axes) {
      if (!Array.isArray(a.v) || a.v.length === 0) bad.push(k + ' -> ' + a.a);
    }
  }
  eq(bad.length, 0, 'empty axes: ' + bad.slice(0, 5).join(', '));
});

// --- percentile-critical invariants -----------------------------------------

test("every 'normalize' coefficient carries a usable ratio", () => {
  const bad = [];
  for (const k of keys) {
    for (const c of EXERCISE_QUALIFIERS[k].coeffs) {
      if (c.t !== 'n') continue;
      if (typeof c.r !== 'number' || !isFinite(c.r) || c.r <= 0) {
        bad.push(k + ' -> ' + c.a + ':' + c.v + ' r=' + c.r);
      }
    }
  }
  eq(bad.length, 0, 'normalize without a ratio: ' + bad.join(', '));
});

test('no ratio is absurd (0.3 .. 3.0)', () => {
  const bad = [];
  for (const k of keys) {
    for (const c of EXERCISE_QUALIFIERS[k].coeffs) {
      if (c.t === 'n' && (c.r < 0.3 || c.r > 3.0)) bad.push(k + ' -> ' + c.a + ':' + c.v + ' r=' + c.r);
    }
  }
  eq(bad.length, 0, 'absurd ratios: ' + bad.join(', '));
});

test('coefficient treatments are only n / p / x', () => {
  const bad = [];
  for (const k of keys) {
    for (const c of EXERCISE_QUALIFIERS[k].coeffs) {
      if (c.t !== 'n' && c.t !== 'p' && c.t !== 'x') bad.push(k + ' -> ' + c.t);
    }
  }
  eq(bad.length, 0, 'bad treatments: ' + bad.join(', '));
});

// After the review corrections, the ONLY surviving normalize family is
// close-grip bench at 0.95 (two peer-reviewed 1RM studies). If a future edit
// adds more, that is a deliberate decision that should break this test and be
// re-argued — not something that slips in.
test('the surviving normalize set is small and is the close-grip bench family', () => {
  const norms = [];
  for (const k of keys) {
    for (const c of EXERCISE_QUALIFIERS[k].coeffs) {
      if (c.t === 'n') norms.push({ k: k, a: c.a, v: c.v, r: c.r });
    }
  }
  assert(norms.length <= 5, 'expected <=5 normalize coefficients, got ' + norms.length +
    ': ' + norms.map((n) => n.k + '/' + n.a + ':' + n.v).join(', '));
  for (const n of norms) {
    assert(
      n.a === 'grip_width' && n.v === 'close',
      'unexpected normalize outside the close-grip family: ' + n.k + ' ' + n.a + ':' + n.v,
    );
  }
});

// --- lookup -----------------------------------------------------------------

test('normalizeExerciseName folds case, punctuation and separators', () => {
  eq(normalizeExerciseName('Close-Grip Lat Pulldown'), 'close grip lat pulldown');
  eq(normalizeExerciseName('  BENCH   PRESS  '), 'bench press');
  eq(normalizeExerciseName("Farmer's Carry"), 'farmers carry');
  eq(normalizeExerciseName(null), '');
});

test('every map key is already normalized (so lookups can hit)', () => {
  const bad = keys.filter((k) => normalizeExerciseName(k) !== k);
  eq(bad.length, 0, 'unnormalized keys: ' + bad.slice(0, 5).join(', '));
});

test('lookup works by display name and is total for unknowns', () => {
  const anyKey = keys[0];
  const spec = qualifierSpecForExercise(EXERCISE_QUALIFIERS[anyKey].name);
  assert(spec, 'display-name lookup should resolve for ' + EXERCISE_QUALIFIERS[anyKey].name);
  eq(qualifierSpecForExercise('No Such Exercise 12345'), null, 'unknown:');
  eq(qualifierSpecForExercise(null), null, 'null:');
});

test('defaultsForExercise returns a value for each of that exercise\'s axes', () => {
  const withAxes = keys.find((k) => EXERCISE_QUALIFIERS[k].axes.length > 0);
  const spec = EXERCISE_QUALIFIERS[withAxes];
  const defs = defaultsForExercise(spec.name);
  eq(Object.keys(defs).length, spec.axes.length, 'one default per axis:');
  for (const a of spec.axes) eq(defs[a.a], a.d, a.a + ' default:');
  eq(Object.keys(defaultsForExercise('No Such Exercise')).length, 0, 'unknown -> {}:');
});

// The founder's headline cases must actually be covered, not merely plausible.
test('the founder\'s motivating exercises carry the expected axes', () => {
  function axesOf(name) {
    const s = qualifierSpecForExercise(name);
    return s ? s.axes.map((a) => a.a) : [];
  }
  assert(axesOf('Lat Pulldown').includes('grip_width'), 'Lat Pulldown should have grip_width');
  assert(axesOf('Bench Press').includes('grip_width'), 'Bench Press should have grip_width');
  const pushdown = axesOf('Triceps Pushdown');
  assert(pushdown.includes('attachment'), 'Triceps Pushdown should have attachment');
  const spec = qualifierSpecForExercise('Triceps Pushdown');
  const att = spec.axes.find((a) => a.a === 'attachment');
  assert(att.c === true, 'the tricep-pushdown attachment axis must allow custom options');
});

console.log('\n' + (passed + failed) + ' tests: ' + passed + ' passed, ' + failed + ' failed\n');
if (failed > 0) process.exit(1);
