-- migrations/20260503_group_streak_credits.sql
-- Phase: D (Group Streak Credits feature)
-- Author: dev-database
-- Date: 2026-05-03
-- Source: group_streak_credits_spec.md
--
-- Implements the full data model for §4 of the Group Streak Credits spec:
--
--   user_weekly_goals       Per-user workout target (§2, §3 decision 7)
--   groups                  Group definition + admin + streak state (§4)
--   group_memberships       Membership roster with lifecycle status (§4, §7)
--   group_week_evaluations  Idempotent audit row per group per ISO week (§4, §5)
--   credit_ledger           Append-only wallet ledger (§4)
--   user_credit_balance     Derived view: SUM(credit_ledger.amount) per user
--   group_active_member_count  Helper view for dormancy and cap checks
--
-- Proposed defaults baked in (§10 — single source of truth; calibrate before launch):
--   GROUP_SIZE_CAP       = 12
--   MAX_GROUPS_PER_USER  = 3   (enforced in application code, not SQL)
--   ACCOUNT_AGE_DAYS     = 30  (enforced in application code)
--   MIN_SESSIONS         = 10  (enforced in application code)
--   WEEKLY_GOAL_FLOOR    = 1   (CHECK constraint on user_weekly_goals)
--   BASE_CREDITS         = 50  (enforced in application code / cron)
--   MULTIPLIER_CAP       = 3.0 (enforced in application code / cron)
--   NEW_JOINER_GRACE_WKS = 2   (enforced in application code / cron)
--   KICK_COOLDOWN_WEEKS  = 4   (enforced in application code)
--
-- Conventions (matching 20260430_initial_schema.sql):
--   * UUID primary keys via gen_random_uuid()
--   * TIMESTAMPTZ for all timestamps
--   * Soft lifecycles via status TEXT columns (no hard deletes on memberships)
--   * RLS enabled on every table; service role handles all cron writes
--   * set_updated_at() trigger function already exists from initial_schema.sql
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- SECTION 1: User weekly goals
-- §2: Each member sets a personal weekly goal ("4 workouts/week", etc.).
-- §7: Mid-week edits queue and apply the following Monday.
-- §3 decision 7: Floor of 1 workout/week.
-- The cron job applies pending_workouts_per_week before evaluating a group.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_weekly_goals (
    user_id                   UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    workouts_per_week         INT  NOT NULL DEFAULT 3
                                  CHECK (workouts_per_week >= 1),
    -- Queued change: applies on pending_applies_at (next Monday 00:00 UTC)
    pending_workouts_per_week INT  CHECK (pending_workouts_per_week >= 1),
    pending_applies_at        DATE,  -- ISO week start (Monday) when pending takes effect
    created_at                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE user_weekly_goals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "user_weekly_goals_self_only" ON user_weekly_goals
    FOR ALL USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

CREATE TRIGGER trg_user_weekly_goals_updated
    BEFORE UPDATE ON user_weekly_goals
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- SECTION 2: Groups
-- §1: Creator picks name and size_cap (2 ≤ cap ≤ 12).
--     Creator becomes admin: can kick members, rename, transfer admin role.
--     Group activates the moment a second member joins.
-- §4 spec DDL faithfully reproduced + invite_token added for share-link invites.
-- invite_token: UUID regenerated on demand by admin; used for the join link.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS groups (
    id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name                 TEXT NOT NULL CHECK (length(name) BETWEEN 1 AND 80),
    size_cap             INT  NOT NULL CHECK (size_cap BETWEEN 2 AND 12),
    admin_user_id        UUID NOT NULL REFERENCES users(id),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    current_streak_weeks INT  NOT NULL DEFAULT 0,
    last_evaluated_week  DATE,   -- ISO week start (Monday) of most recent evaluation
    -- Share-link token. Regenerated by admin whenever old link should be invalidated.
    invite_token         UUID NOT NULL DEFAULT gen_random_uuid(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- idx_groups_last_evaluated: fast scan for the weekly cron job (§5)
CREATE INDEX IF NOT EXISTS idx_groups_last_evaluated
    ON groups (last_evaluated_week);

-- idx_groups_admin: admin-lookup for permission checks
CREATE INDEX IF NOT EXISTS idx_groups_admin
    ON groups (admin_user_id);

ALTER TABLE groups ENABLE ROW LEVEL SECURITY;

-- NOTE: "groups_visible_to_members" policy is defined AFTER group_memberships is
-- created (see below) because the policy body references group_memberships and
-- Postgres validates the reference immediately at CREATE POLICY time.

-- Only the admin can update group metadata (name, invite_token).
CREATE POLICY "groups_admin_update" ON groups
    FOR UPDATE USING (auth.uid() = admin_user_id);

-- Group creation is done by the creating user; INSERT allowed when caller = admin.
-- (Application code enforces the eligibility gate and group-cap before the INSERT.)
CREATE POLICY "groups_insert_by_creator" ON groups
    FOR INSERT WITH CHECK (auth.uid() = admin_user_id);

CREATE TRIGGER trg_groups_updated
    BEFORE UPDATE ON groups
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- SECTION 3: Group memberships
-- §4 spec DDL + kick_cooldown_until for the 4-week rejoin cooldown (§7, §8).
-- status lifecycle: 'active' → 'left' (voluntary) | 'kicked' (admin action)
-- joined_at determines first eligible week: member eligible for weeks starting
--   AFTER the Monday following joined_at (see §7 — week-boundary join rule).
-- left_at is set on leave/kick; used by cron for the 48h kick rule (§7).
-- kick_cooldown_until: blocks rejoin for 4 weeks after a kick (§7, §8).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS group_memberships (
    group_id             UUID NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    user_id              UUID NOT NULL REFERENCES users(id),
    joined_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    left_at              TIMESTAMPTZ,
    status               TEXT NOT NULL DEFAULT 'active'
                             CHECK (status IN ('active', 'left', 'kicked')),
    kick_cooldown_until  TIMESTAMPTZ,  -- NULL unless kicked; blocks rejoin until this ts
    PRIMARY KEY (group_id, user_id)
);

-- Active-members-per-group: dominant query for cron + size-cap enforcement
CREATE INDEX IF NOT EXISTS idx_group_memberships_group_status
    ON group_memberships (group_id, status);

-- User's active memberships: concurrent-group-cap enforcement (§3 decision 5)
CREATE INDEX IF NOT EXISTS idx_group_memberships_user_active
    ON group_memberships (user_id)
    WHERE status = 'active';

-- last_evaluated_week scan in cron: also needs a user_id lookup for goal checks
CREATE INDEX IF NOT EXISTS idx_group_memberships_user
    ON group_memberships (user_id);

ALTER TABLE group_memberships ENABLE ROW LEVEL SECURITY;

-- Members can see all memberships (active + past) in groups they belong to.
CREATE POLICY "memberships_visible_to_group_members" ON group_memberships
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM group_memberships gm2
            WHERE gm2.group_id = group_memberships.group_id
              AND gm2.user_id  = auth.uid()
              AND gm2.status   = 'active'
        )
    );

-- A user can insert their own membership row (when joining via API).
CREATE POLICY "memberships_self_insert" ON group_memberships
    FOR INSERT WITH CHECK (auth.uid() = user_id);

-- A member can update their own row (to leave); admin can update any row in their groups.
CREATE POLICY "memberships_self_or_admin_update" ON group_memberships
    FOR UPDATE USING (
        auth.uid() = user_id
        OR EXISTS (
            SELECT 1 FROM groups g
            WHERE g.id = group_memberships.group_id
              AND g.admin_user_id = auth.uid()
        )
    );

-- Deferred: groups SELECT policy that cross-references group_memberships.
-- Must appear after group_memberships is created (circular FK dependency).
CREATE POLICY "groups_visible_to_members" ON groups
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM group_memberships gm
            WHERE gm.group_id = groups.id
              AND gm.user_id  = auth.uid()
              AND gm.status   = 'active'
        )
    );

-- ---------------------------------------------------------------------------
-- SECTION 4: Group week evaluations
-- §4, §5: Idempotent audit row per (group_id, week_start).
--   credits_per_member = 0 on failure, > 0 on success.
--   Primary key blocks double-inserts — replays are no-ops (§5, §9).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS group_week_evaluations (
    group_id            UUID NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    week_start          DATE NOT NULL,   -- ISO week start (Monday, UTC)
    eligible_members    INT  NOT NULL,
    members_hit_goal    INT  NOT NULL,
    streak_weeks_after  INT  NOT NULL,
    credits_per_member  INT  NOT NULL,   -- 0 on failure
    evaluated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (group_id, week_start)
);

-- History display: most recent first per group
CREATE INDEX IF NOT EXISTS idx_group_week_evals_group
    ON group_week_evaluations (group_id, week_start DESC);

ALTER TABLE group_week_evaluations ENABLE ROW LEVEL SECURITY;

-- Current and past members can read evaluation history.
CREATE POLICY "evaluations_visible_to_members" ON group_week_evaluations
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM group_memberships gm
            WHERE gm.group_id = group_week_evaluations.group_id
              AND gm.user_id  = auth.uid()
        )
    );

-- Only the service role (cron) inserts evaluation rows; client writes blocked.

-- ---------------------------------------------------------------------------
-- SECTION 5: Credit ledger (append-only)
-- §4: Wallet balance is NEVER stored — it is always derived as SUM(amount).
-- Positive amounts = earned; negative = spent.
-- source: 'group_streak' | 'cosmetic_purchase' | 'admin_adjustment'
--   cosmetic_purchase and admin_adjustment reserved for future use.
-- group_id + week_start populated for 'group_streak' entries (audit trail).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS credit_ledger (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID NOT NULL REFERENCES users(id),
    amount      INT  NOT NULL,
    source      TEXT NOT NULL
                    CHECK (source IN ('group_streak', 'cosmetic_purchase', 'admin_adjustment')),
    group_id    UUID REFERENCES groups(id),
    week_start  DATE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Fast balance derivation and paginated history display
CREATE INDEX IF NOT EXISTS idx_credit_ledger_user_created
    ON credit_ledger (user_id, created_at DESC);

ALTER TABLE credit_ledger ENABLE ROW LEVEL SECURITY;

-- Users can only read their own ledger.
CREATE POLICY "credit_ledger_self_select" ON credit_ledger
    FOR SELECT USING (auth.uid() = user_id);

-- All ledger writes come from the service role (cron, cosmetic shop).
-- No direct client INSERT/UPDATE/DELETE.

-- ---------------------------------------------------------------------------
-- SECTION 6: Derived views
-- ---------------------------------------------------------------------------

-- user_credit_balance: wallet balance per user (§4)
-- Usage: SELECT balance FROM user_credit_balance WHERE user_id = $1
CREATE OR REPLACE VIEW user_credit_balance AS
    SELECT user_id, COALESCE(SUM(amount), 0) AS balance
    FROM credit_ledger
    GROUP BY user_id;

-- group_active_member_count: active headcount per group
-- Used by application code for size-cap checks and dormancy detection.
CREATE OR REPLACE VIEW group_active_member_count AS
    SELECT group_id, COUNT(*) AS active_count
    FROM group_memberships
    WHERE status = 'active'
    GROUP BY group_id;

-- ---------------------------------------------------------------------------
-- SUMMARY
-- 5 tables, 2 views, 7 indexes, 12 RLS policies, 2 triggers.
-- All application-layer constants (caps, rates, multiplier) live in:
--   server/routes/groups.js  (API layer)
--   server/cron/group-streaks.js  (evaluation cron)
-- ---------------------------------------------------------------------------
